apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
      name: argocd-deploy
      namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/tapashdeb/TheWorldClock.git
        targetRevision: HEAD
        path: master
    destination:
        server: https://kubernetes.default.svc
        namespace: myapp

    syncPolicy:
        syncOptions:
        - CreateAutomatically=true

        automated: 
            selfHeal: true
            prune: true